#!/bin/bash

echo "🚀 Launching AgriForecast.ai with Mobile PWA Features..."
echo "=================================================="
echo ""
echo "🌾 Starting your enhanced agricultural platform..."
echo ""
echo "✨ NEW FEATURES AVAILABLE:"
echo "  📱 Mobile-responsive navigation"
echo "  🔄 Progressive Web App (PWA) support"
echo "  💾 Offline capabilities"
echo "  🎯 Touch-optimized interface"
echo "  📲 App installation prompt"
echo ""
echo "🌐 Platform will be available at:"
echo "   Desktop: http://localhost:8501"
echo "   Mobile:  http://[your-ip]:8501"
echo ""
echo "📱 MOBILE TESTING:"
echo "   1. Open on your phone's browser"
echo "   2. Look for 'Install App' prompt"
echo "   3. Test the hamburger menu (☰)"
echo "   4. Try going offline to test PWA"
echo ""
echo "🔧 Default Login:"
echo "   Username: anand"
echo "   Password: password123"
echo ""
echo "Press Ctrl+C to stop the server"
echo "=================================================="
echo ""

# Run the enhanced platform
streamlit run agriforecast_modern.py --server.port 8501 --server.address 0.0.0.0
